[manager]

prepend_keymap = [
  { on = [ "g", "e" ], run = "arrow 99999999", desc = "Bottom" },
  { on = "P", run = "plugin --sync hide-preview", desc = "Hide preview" },

  # for yazi v0.4 upcoming release
	# Toggle
	# { on = "<Space>", run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },
	# { on = "<C-a>",   run = "toggle_all --state=on", desc = "Select all files" },
	# { on = "<C-r>",   run = "toggle_all",            desc = "Invert selection of all files" },

  # drop to shell
  { on = "<C-Space>", run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

  # custom linemodes
	{ on = [ "m", "b" ], run = "linemode btimev2", desc = "Set linemode to btimev2" },
	{ on = [ "m", "m" ], run = "linemode mtimev2", desc = "Set linemode to mtimev2" },

  # sorting
	{ on = [ ",", "m" ], run = [ "sort modified --reverse", "linemode mtimev2" ], desc = "Sort by modified time" },
	{ on = [ ",", "M" ], run = [ "sort modified --reverse=no", "linemode mtimev2" ], desc = "Sort by modified time (reverse)" },
	{ on = [ ",", "b" ], run = [ "sort created --reverse", "linemode btimev2" ], desc = "Sort by created time" },
	{ on = [ ",", "b" ], run = [ "sort created --reverse=no", "linemode btimev2" ], desc = "Sort by created time (reverse)" },

  # jump to directory
	{ on = [ "g", "C" ], run = "cd ~/.local/share/chezmoi", desc = "Jump to Chezmoi" },
	{ on = [ "g", "d" ], run = "cd ~/Downloads", desc = "Jump to ~/Downloads" },
	{ on = [ "g", "D" ], run = "cd ~/Documents", desc = "Jump to ~/Documents" },
	{ on = [ "g", "p" ], run = "cd ~/Pictures", desc = "Jump to ~/Pictures" },
	{ on = [ "g", "v" ], run = "cd ~/Videos", desc = "Jump to ~/Videos" },
	{ on = [ "g", "m" ], run = "cd /run/media", desc = "Jump to /run/media" },
	{ on = [ "g", "r" ], run = "cd ~/repos", desc = "Jump to ~/repos" },
]

append_keymap = [
  # edit pictures with satty
  { on = "<C-i>", run = 'shell "satty --fullscreen -f $@ -o $(xdg-user-dir PICTURES)/satty_edits/$(date "+%Y-%m-%d_%H:%M:%S").png" --confirm', desc = "Edit with Satty" }
]


[input]

prepend_keymap = [
  # { on = "<Esc>", run = "close", desc = "Cancel input"}
]
