[manager]

prepend_keymap = [
  { on = [ "g", "e" ], run = "arrow 99999999", desc = "Bottom" },

  # hide preview plugin
  { on = "P", run = "plugin hide-preview", desc = "Toggle preview" },

	# toggle
	{ on = "<Space>", run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = "<C-a>",   run = "toggle_all --state=on", desc = "Select all files" },
	{ on = "<C-r>",   run = "toggle_all",            desc = "Invert selection of all files" },

  # drop to shell
  { on = "<C-Space>", run = 'shell "$SHELL" --block', desc = "Open shell here" },

  # linemodes
	{ on = [ "m", "b" ], run = "linemode btimev2", desc = "Birth Time" },
	{ on = [ "m", "m" ], run = "linemode mtimev2", desc = "Modified Time" },
	{ on = [ "m", "s" ], run = "linemode size", desc = "Size" },
	{ on = [ "m", "p" ], run = "linemode permissions", desc = "Permissions" },
	{ on = [ "m", "o" ], run = "linemode owner", desc = "Owner" },
	{ on = [ "m", "n" ], run = "linemode none", desc = "None" },

  # sorting
	{ on = [ ",", "m" ], run = [ "sort mtime --reverse", "linemode mtimev2" ], desc = "Sort by modified time" },
	{ on = [ ",", "M" ], run = [ "sort mtime --reverse=no", "linemode mtimev2" ], desc = "Sort by modified time (reverse)" },
	{ on = [ ",", "b" ], run = [ "sort btime --reverse", "linemode btimev2" ], desc = "Sort by birth time" },
	{ on = [ ",", "b" ], run = [ "sort btime  --reverse=no", "linemode btimev2" ], desc = "Sort by birth time (reverse)" },

  # jump to directory
	{ on = [ "g", "C" ], run = "cd ~/.local/share/chezmoi", desc = "Jump to Chezmoi" },
	{ on = [ "g", "d" ], run = "cd ~/Downloads", desc = "Jump to ~/Downloads" },
	{ on = [ "g", "D" ], run = "cd ~/Documents", desc = "Jump to ~/Documents" },
	{ on = [ "g", "p" ], run = "cd ~/Pictures", desc = "Jump to ~/Pictures" },
	{ on = [ "g", "v" ], run = "cd ~/Videos", desc = "Jump to ~/Videos" },
	{ on = [ "g", "m" ], run = "cd /run/media", desc = "Jump to /run/media" },
	{ on = [ "g", "r" ], run = "cd ~/repos", desc = "Jump to ~/repos" },
]

append_keymap = [
  # edit pictures with satty
  { on = "<C-i>", run = 'shell "satty --fullscreen -f $@ -o $(xdg-user-dir PICTURES)/satty_edits/$(date "+%Y-%m-%d_%H:%M:%S").png" --confirm', desc = "Edit with Satty" }
]


[input]

# this is to exit input immediatly and avoid using vim keybinds inside it
# prepend_keymap = [
  # { on = "<Esc>", run = "close", desc = "Cancel input"}
# ]
