"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]

cwd = { fg = "#777777", italic = true }
hovered = { fg = "#191919", bg = "#7575FF" }
# hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#222222", bg = "#f65555", bold = true }
find_position = { fg = "#ff0000", bg = "#192b38", bold = true }

marker_copied   = { fg = "#191919", bg = "green" }
marker_cut      = { fg = "#191919", bg = "red" }
marker_marked   = { fg = "#191919", bg = "magenta" }
marker_selected = { fg = "#191919", bg = "blue" }

tab_active   = { fg = "#cccccc", bg = "#1b1b1b" }
tab_inactive = { fg = "#777777", bg = "#1b1b1b" }
tab_width    = 1

count_copied   = { fg = "#191919", bg = "green" }
count_cut      = { fg = "#191919", bg = "red" }
count_selected = { fg = "#191919", bg = "blue" }

border_symbol = "│"
border_style  = { fg = "yellow" }

[mode]

normal_main = { bg = "#1b1b1b", fg = "yellow",  bold = true }
normal_alt  = { fg = "#cccccc", bg = "#1b1b1b" }

# Select mode
select_main = { bg = "#1b1b1b", fg = "green", bold = true }
select_alt  = { fg = "#cccccc", bg = "#1b1b1b" }

# Unset mode
unset_main = { bg = "#1b1b1b", fg ="red",  bold = true }
unset_alt  = { fg = "red", bg = "#1b1b1b" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3b4261", bg = "#3b4261" }

progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

perm_sep   = { fg = "darkgray" }
perm_type  = { fg = "green" }
perm_read  = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec  = { fg = "cyan" }

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

[confirm]
border     = { fg = "blue" }
title      = { fg = "blue" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border = { fg = "blue" }
title  = { fg = "blue" }


[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

[pick]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }

[help]
on      = { fg = "green" }
run     = { fg = "#B26EF7" }
desc    = {fg = "#cccccc"}
hovered = { reversed = false, bg = "#333333", bold = true }
footer  = { fg = "#cccccc", bg = "#333333" }
