theme = "tokyonight"

[editor]
mouse = true
cursorline = false
cursorcolumn = false
line-number = "absolute"
color-modes = true

[editor.cursor-shape]
insert = "block"

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽","╎""
skip-levels = 0

[editor.statusline]
left = ["mode","file-name", "spinner","version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
