#!/bin/sh

# ··· VARIABLES ···
mod=Super
term=foot
termclient=footclient
browser=librewolf
termfilemanager=yazi
filemanager=nautilus -w
menu="fuzzel --config ~/.config/fuzzel/fuzzel-square.ini"
notes=logseq
system_monitor=htop

# ··· ENVIRONMENT VARIABLES ···
export XDG_SESSION_TYPE='wayland'
export XDG_SESSION_DESKTOP='river'
export XDG_CURRENT_DESKTOP='river'
export QT_QPA_PLATFORM='wayland'
export SDL_VIDEODRIVER='wayland'
export _JAVA_AWT_WM_NONREPARENTING='1'
export PATH="$PATH:/home/alec/.local/bin"

# ··· ROUTINE ···
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river &
foot -s &
waybar -c ~/.config/waybar/river/config-river-bottom.jsonc -s ~/.config/waybar/river/style-river-bottom.css &
# swaybg -m fill -i ~/Pictures/wallpapers/vaporwave/vw05.png &
# swaybg -m fill -i ~/Pictures/wallpapers/synthwave/sw06.png &
# swaybg -m fill -i ~/Pictures/wallpapers/vaporwave/vw21.jpg &
# swaybg -m fill -i ~/Pictures/wallpapers/synthwave/sw03.png &
swaybg -m fill -i ~/Pictures/wallpapers/digital_landscape/dl18.png &
gammastep &
swayidle -w -C ~/.config/swayidle/ensure-lock-minimal &
swayidle -C ~/.config/swayidle/idle-minimal &
# swaync -s ~/.config/swaync/style_square.css &
mako -c ~/.config/mako/config-square &
udiskie -a &
# shikane &
kanshi &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
cliphist wipe && wl-paste --watch cliphist store &

# ··· OPTIONS ···
riverctl background-color 0x1A1B26FF
riverctl border-color-focused 0xAD8EE6FF
riverctl border-color-unfocused 0x5C6691FF
riverctl border-width 3
riverctl focus-follows-cursor normal
riverctl default-layout rivertile
riverctl default-attach-mode top
rivertile -view-padding 3 -outer-padding 3 -main-ratio 0.5 -main-location left &

# ←bsp layout→
# riverctl default-layout bsp-layout
# river-bsp-layout --inner-gap 5 --outer-gap 10 --split-perc 0.5 &

# ···INPUT ···

# pointer
riverctl hide-cursor timeout 20000
riverctl input pointer-1133-16471-Logitech_M280/320/275 pointer-accel -0.35

# keyboard
riverctl keyboard-layout latam
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl set-repeat 40 250

# touchpad
riverctl input pointer-1267-12734-ELAN06FA:00_04F3:31BE_Touchpad pointer-accel 1.0
riverctl input pointer-1267-12734-ELAN06FA:00_04F3:31BE_Touchpad accel-profile flat
riverctl input pointer-1267-12734-ELAN06FA:00_04F3:31BE_Touchpad tap enabled
riverctl input pointer-1267-12734-ELAN06FA:00_04F3:31BE_Touchpad tap-button-map left-right-middle
riverctl input pointer-1267-12734-ELAN06FA:00_04F3:31BE_Touchpad natural-scroll enabled
riverctl input pointer-1267-12734-ELAN06FA:00_04F3:31BE_Touchpad scroll-factor 0.2
riverctl input pointer-1267-12734-ELAN06FA:00_04F3:31BE_Touchpad drag enabled

# ··· KEYBINDS ···

# launch
riverctl map normal $mod B spawn "$browser"
riverctl map normal $mod D spawn "$menu"
riverctl map normal $mod Y spawn "$termclient -e $termfilemanager"
riverctl map normal $mod I spawn "$termclient -e $system_monitor"
riverctl map normal $mod Return spawn "$termclient"
riverctl map normal $mod+Shift Return spawn "$term"
riverctl map normal $mod Insert spawn "$termclient -T 'wifi420' -e impala"
riverctl map normal $mod Delete spawn "$termclient -T 'bluetooth420' -e bluetui"

# river
riverctl map normal $mod+Shift Backspace exit
riverctl map normal $mod+Alt+Control L spawn "hyprlock -c ~/.config/hypr/hyprlock/hl-minimal.conf"

# panels
riverctl map normal $mod Minus spawn "swaync-client -t"
riverctl map normal $mod O spawn "nwg-bar -t logout_river.json -s logout_square.css"
riverctl map normal $mod Bar spawn "wlr-which-key ~/.config/wlr-which-key/quickpanel_square.yaml"

# layout
riverctl map normal $mod Comma send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod Period send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal $mod+Shift Comma send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift Period send-layout-cmd rivertile "main-count -1"

# windows
riverctl map normal $mod C close
riverctl map normal $mod F toggle-fullscreen
riverctl map normal $mod V toggle-float
riverctl map normal $mod G zoom
riverctl map normal $mod Left focus-view left
riverctl map normal $mod Down focus-view down
riverctl map normal $mod Up focus-view up
riverctl map normal $mod Right focus-view right
riverctl map normal $mod Tab focus-view next
riverctl map normal $mod+Shift Tab focus-view previous
riverctl map normal $mod+Shift Left swap left
riverctl map normal $mod+Shift Down swap down
riverctl map normal $mod+Shift Up swap up
riverctl map normal $mod+Shift Right swap right
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

# move mode (floating)
riverctl declare-mode move
riverctl map normal $mod M enter-mode move  
riverctl map move $mod M enter-mode normal
riverctl map move $mod N enter-mode normal  
riverctl map move $mod R enter-mode resize
riverctl map -repeat move None H move left 69
riverctl map -repeat move None J move down 69
riverctl map -repeat move None K move up 69
riverctl map -repeat move None L move right 69

# resize mode (floating)
riverctl declare-mode resize
riverctl map normal $mod R enter-mode resize
riverctl map resize $mod R enter-mode normal  
riverctl map resize $mod N enter-mode normal  
riverctl map resize $mod M enter-mode move  
riverctl map -repeat resize None H resize horizontal -30
riverctl map -repeat resize None J resize vertical -30
riverctl map -repeat resize None K resize vertical 30
riverctl map -repeat resize None L resize horizontal 30

# windows → monitors
riverctl map normal $mod+Control Left focus-output left
riverctl map normal $mod+Control Down focus-output down
riverctl map normal $mod+Control Up focus-output up
riverctl map normal $mod+Control Right focus-output right
riverctl map normal $mod+Alt Left send-to-output -current-tags left
riverctl map normal $mod+Alt Up send-to-output -current-tags up
riverctl map normal $mod+Alt Down send-to-output -current-tags down
riverctl map normal $mod+Alt Right send-to-output -current-tags right

# vim-like
riverctl map normal $mod K focus-view up
riverctl map normal $mod L focus-view right
riverctl map normal $mod J focus-view down
riverctl map normal $mod H focus-view left
riverctl map normal $mod+Shift K swap up
riverctl map normal $mod+Shift L swap right
riverctl map normal $mod+Shift J swap down
riverctl map normal $mod+Shift H swap left
riverctl map normal $mod+Control H focus-output left
riverctl map normal $mod+Control J focus-output down
riverctl map normal $mod+Control K focus-output up
riverctl map normal $mod+Control L focus-output right
riverctl map normal $mod+Alt H send-to-output -current-tags left
riverctl map normal $mod+Alt J send-to-output -current-tags down
riverctl map normal $mod+Alt K send-to-output -current-tags up
riverctl map normal $mod+Alt L send-to-output -current-tags right

# tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Alt $i toggle-focused-tags $tags
    riverctl map normal $mod+Control $i toggle-view-tags $tags
done

# 10th tag
riverctl map normal $mod 0 set-focused-tags 512
riverctl map normal $mod+Shift 0 set-view-tags 512
riverctl map normal $mod+Alt 0 toggle-focused-tags 512
riverctl map normal $mod+Control 0 toggle-view-tags 512

# all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod A set-focused-tags $all_tags
riverctl map normal $mod+Shit A set-view-tags $all_tags

# previous tags
riverctl map normal $mod S send-to-previous-tags  
riverctl map normal $mod P focus-previous-tags  

# music
music_tag=$((1 << 10 ))
riverctl map normal $mod Apostrophe spawn "~/scripts/launch/tags/river/music-tag.sh"
riverctl map normal $mod+Shit Apostrophe set-view-tags ${music_tag}
riverctl map normal $mod+Alt Apostrophe toggle-focused-tags ${music_tag}
all_but_music_tag=$(( ((1 << 32) - 1) ^ $music_tag ))
riverctl spawn-tagmask ${all_but_music_tag}

# mail
mail_tag=$((1 << 11 ))
riverctl map normal $mod Questiondown spawn "~/scripts/launch/tags/river/mail-tag.sh"
riverctl map normal $mod+Shift Questiondown set-view-tags ${mail_tag}
riverctl map normal $mod+Alt Questiondown toggle-focused-tags ${mail_tag}
all_but_music_tag=$(( ((1 << 32) - 1) ^ $mail_tag ))
riverctl spawn-tagmask ${all_but_mail_tag}

# window manager inception³
riverctl declare-mode passthrough
riverctl map normal $mod F11 enter-mode passthrough
riverctl map passthrough $mod F11 enter-mode normal

# volume, brightness, screenshots and music
for mode in normal locked
do
    # volume
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+'
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-'
    riverctl map -repeat $mode None XF86AudioMute         spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
    riverctl map -repeat $mode None XF86AudioMicMute      spawn "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"

    # brightness
    riverctl map -repeat $mode None XF86MonBrightnessUp   spawn 'brightnessctl s 5%+'
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn 'brightnessctl s 5%-'

    # screnshots
    riverctl map $mode None Print spawn '~/scripts/screenshots/river/allmonitors.sh'
    riverctl map $mode $mod Print spawn '~/scripts/screenshots/river/allmonitors-edit.sh'
    riverctl map $mode None+Control Print spawn '~/scripts/screenshots/river/area.sh'

    # music
    riverctl map $mode $mod Q spawn 'mpc prev'
    riverctl map $mode $mod W spawn 'mpc toggle'
    riverctl map $mode $mod E spawn 'mpc next'
    riverctl map $mode $mod+Shift Q spawn 'mpc seek -10'
    riverctl map $mode $mod+Shift W spawn 'mpc stop'
    riverctl map $mode $mod+Shift E spawn 'mpc seek +10'
    riverctl map $mode $mod+Control Q spawn 'mpc seek 0'
    riverctl map $mode $mod+Control W spawn 'mpc random'
done

# ·· RULES ···

# decorations
riverctl rule-add ssd

# float
riverctl rule-add -app-id 'org.twosheds.iwgtk' float
riverctl rule-add -app-id 'blueberry.py' float
riverctl rule-add -app-id 'hyprland-share-picker' float
riverctl rule-add -app-id 'galculator' float
riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' float
riverctl rule-add -app-id 'imv' float
riverctl rule-add -title 'Open File' float
riverctl rule-add -title 'Open Folder' float
riverctl rule-add -title 'File Upload' float
riverctl rule-add -title 'Select File' float
riverctl rule-add -title 'Browse Files' float
riverctl rule-add -title 'Save As' float
riverctl rule-add -title 'Save Image' float
riverctl rule-add -title 'Library' float
riverctl rule-add -title 'Unlock Keyring' float
riverctl rule-add -title 'Enter name of file to save to…' float
riverctl rule-add -title 'hyprland-share-picker' float
riverctl rule-add -title 'gcr-prompter' float
riverctl rule-add -title 'wifi420' float
riverctl rule-add -title 'bluetooth420' float

# size
riverctl rule-add -app-id 'org.twosheds.iwgtk' dimensions 550 700
riverctl rule-add -app-id 'org.pulseaudio.pavucontrol' dimensions 700 500
riverctl rule-add -title 'wifi420' dimensions 850 900
riverctl rule-add -title 'bluetooth420' dimensions 755 500

# position
riverctl rule-add -title 'wifi420' position 535 72 # for waybar bottomposition
riverctl rule-add -title 'bluetooth420' position 582 272 # for waybar bottomposition
# riverctl rule-add -title 'wifi410' position 535 107 # for waybar top position
# riverctl rule-add -title 'bluetooth420' position 582 307 # for waybar top position

# location
riverctl rule-add -app-id 'music420' tags $((1 << 10))
riverctl rule-add -app-id 'mail80085' tags $((1 << 11))
