"ui.selection" = { bg = "#333333" }
"ui.selection.primary" = { bg = "#333333" }

"ui.background" = {}

"ui.cursor" = { fg = "#191919", bg = "#ffff66" }
"ui.cursor.primary.normal" = { fg = "#191919", bg = "#ffff66" }
"ui.cursor.primary.insert" = { fg = "#191919", bg = "#b266ff" }
"ui.cursor.primary.select" = { fg = "#191919", bg = "#77ff33" }
"ui.cursor.normal" = { fg = "#191919", bg = "#999900" }
"ui.cursor.insert" = { fg = "#191919", bg = "#4c0099" }
"ui.cursor.select" = { fg = "#191919", bg = "#4d9900" }

"ui.linenr" = { fg = "#777777" }
"ui.linenr.selected" = { fg = "#ffff66" }
# "ui.gutter" = { bg = "#333333" }

"ui.text" = { fg = "#dddddd"}
"ui.text.inactive" = { fg = "#555555"}

"ui.statusline" = { fg = "#cccccc", bg = "#333333" }
"ui.statusline.inactive" = { bg = "#222222" }
"ui.statusline.normal" = { bg = "#333333", fg = "#ffff66", modifiers = [ "bold" ] }
"ui.statusline.insert" = { bg = "#333333", fg = "#b266ff", modifiers = [ "bold" ] }
"ui.statusline.select" = { bg = "#333333", fg = "#77ee00", modifiers = [ "bold" ] }

# "ui.bufferline" = { fg = "#ff0000", bg = "#333333" }
# "ui.bufferline.active" = { fg = "#ff0000", bg = "#333333" }

"ui.virtual.indent-guide" = { fg = "#555555" }
"ui.virtual.ruler" = { fg = "#555555" }
"ui.virtual.jump-label" = { fg = "#66ffff" }
"ui.match" = { fg = "ff6666" }

"ui.window" = { fg ="#555555"}

# "warning" = { fg = "#ffb366" }
# "error" = { fg = "#ff6666"}
# "hint" = { fg = "#66b2ff"}

# "diagnostic.hint" = { fg = "#ffb366" }
# "diagnostic.warning" = { fg = "#ffb366" }
# "diagnostic.error" = { fg = "#ff6666"}
# "diagnostic.hint" = { fg = "#66b2ff"}
# "diagnostic.unnecesary" = { fg = "#ffb366" }
# "diagnostic.depecrated" = { fg = "#ffb366" }

# syntax
"comment" = { fg = "#777777", modifiers = [ "italic" ] }
"variable" = { fg = "#ebeb47" }
"label" = { fg = "#ffff66" }
"string" = { fg = "#ff666" }



[palette]
red = "#ff6666"
orange = "#ffb366"
green = "#b3ff66"
yellow = "#ffff66"
blue = "#66b2ff"
magenta = "#b266ff"
cyan = "#66ffff"

