
"ui.background" = { bg = "{}"}
"ui.text" = { fg = "fg" }
"ui.text.inactive" = { fg = "#555555" }

"ui.selection" = { bg = "#333333" }
"ui.selection.primary" = { bg = "#333333" }

# cursor
"ui.cursor" = { fg = "#background", bg = "#d9d926"}
"ui.cursor.primary.normal" = { fg = "#1b1b1b", bg = "#d9d926" }
"ui.cursor.primary.insert" = { fg = "#1b1b1b", bg = "#267fd9" }
"ui.cursor.primary.select" = { fg = "#1b1b1b", bg = "#80d926" }
"ui.cursor.normal" = { fg = "#1b1b1b", bg = "#999933" }
"ui.cursor.insert" = { fg = "#1b1b1b", bg = "#336699" }
"ui.cursor.select" = { fg = "#1b1b1b", bg = "#669933" }

# line numbers
"ui.linenr" = { fg = "#777777" }
"ui.linenr.selected" = { fg = "#d9d926" }
# "ui.gutter" = { bg = "#333333" }

# statusline
"ui.statusline" = { fg = "#cccccc", bg = "#333333" }
"ui.statusline.inactive" = { fg = "#777777", bg = "#222222" }
"ui.statusline.normal" = { bg = "#333333", fg = "#d9d926", modifiers = [ "bold" ] }
"ui.statusline.insert" = { bg = "#333333", fg = "#267fd9", modifiers = [ "bold" ] }
"ui.statusline.select" = { bg = "#333333", fg = "#80d926", modifiers = [ "bold" ] }

# bufferline
"ui.bufferline" = { fg = "#777777", bg = "#333333" }
"ui.bufferline.active" = { fg = "#cccccc", bg = "#333333" }

"ui.virtual.indent-guide" = { fg = "#555555" }
"ui.virtual.ruler" = { bg = "#555555" }
"ui.virtual.jump-label" = { fg = "#26d9d9" }
"ui.match" = { fg = "#d92626" }
"ui.window" = { fg = "#555555" }

"diagnostic.warning" = { bg = "#d97f26", fg = "#19191900" }
"diagnostic.error" = { fg = "#d92626"}
"diagnostic.hint" = { fg = "#267fd9" }
"diagnostic.unnecesary" = { fg = "#d97f26" }
"diagnostic.depecrated" = { fg = "#d97f26" }

"warning" = { fg = "d97f26" }
"error" = { fg = "#d92626"}
"hint" = { fg = "#267fd9"}

# syntax
"comment" = { fg = "#777777", modifiers = [ "italic" ] }
"variable" = { fg = "#d9d926" }
"label" = { fg = "#d9d926" }
"string" = { fg = "#267fd9" }
"keyword" = { fg = "#7f26d9" }
"attribute" = { fg = "#80d926" }
"types" = { fg = "#d92626" }
"constant" = { fg = "#26d9d9"}

"diff.plus" = { fg = "#80d926" }
"diff.minus" = { fg = "#d92626" }
"diff.delta" = { fg = "#267fd9" }

[palette]
background= "{}"
foreground = "#cccccc"
fg = "#cccccc"
fgdim = "#777777"
red = "#d92626"
orange ="#d97f26"
green = "#80d926"
yellow = "#d9d926"
blue = "#267fd9"
magenta ="#7f26d9"
cyan = "#26d9bb"

