
"ui.background" = { bg = "{}"}
"ui.text" = { fg = "fg" }
"ui.text.inactive" = { fg = "#555555" }

"ui.selection" = { bg = "#333333" }
"ui.selection.primary" = { bg = "#333333" }

# cursor
"ui.cursor" = { fg = "#1b1b1b", bg = "#f6f655"}
"ui.cursor.primary.normal" = { fg = "#1b1b1b", bg = "#f6f655" }
"ui.cursor.primary.insert" = { fg = "#1b1b1b", bg = "#9c9cff" }
"ui.cursor.primary.select" = { fg = "#1b1b1b", bg = "#a6f655" }
"ui.cursor.normal" = { fg = "#1b1b1b", bg = "#999933" }
"ui.cursor.insert" = { fg = "#1b1b1b", bg = "#336699" }
"ui.cursor.select" = { fg = "#1b1b1b", bg = "#669933" }

# line numbers
"ui.linenr" = { fg = "#777777" }
"ui.linenr.selected" = { fg = "#f6f655" }
# "ui.gutter" = { bg = "#333333" }

# statusline
"ui.statusline" = { fg = "#cccccc", bg = "#333333" }
"ui.statusline.inactive" = { fg = "#777777", bg = "#222222" }
"ui.statusline.normal" = { bg = "#333333", fg = "#f6f655", modifiers = [ "bold" ] }
"ui.statusline.insert" = { bg = "#333333", fg = "#7575FF", modifiers = [ "bold" ] }
"ui.statusline.select" = { bg = "#333333", fg = "#a6f655", modifiers = [ "bold" ] }

# bufferline
"ui.bufferline" = { fg = "#777777", bg = "#333333" }
"ui.bufferline.active" = { fg = "#cccccc", bg = "#333333" }

"ui.virtual.indent-guide" = { fg = "#555555" }
"ui.virtual.ruler" = { bg = "#555555" }
"ui.virtual.jump-label" = { fg = "#55f6f6" }
"ui.match" = { fg = "#f65555" }
"ui.window" = { fg = "#555555" }

"diagnostic.warning" = { bg = "#f6a655", fg = "#19191900" }
"diagnostic.error" = { fg = "#f65555"}
"diagnostic.hint" = { fg = "#7575FF" }
"diagnostic.unnecesary" = { fg = "#f6a655" }
"diagnostic.depecrated" = { fg = "#f6a655" }

"warning" = { fg = "#f6a655" }
"error" = { fg = "#f65555"}
"hint" = { fg = "#7575FF"}

# syntax
"comment" = { fg = "#777777", modifiers = [ "italic" ] }
"variable" = { fg = "#f6f655" }
"label" = { fg = "#f6f655" }
"string" = { fg = "#7575FF" }
"keyword" = { fg = "#f655f6" }
"attribute" = { fg = "#a6f655" }
"types" = { fg = "#f65555" }
"constant" = { fg = "#55f6f6"}

"diff.plus" = { fg = "#a6f655" }
"diff.minus" = { fg = "#f65555" }
"diff.delta" = { fg = "#7575FF" }

"markup.bold" = { fg = "#cccccc", modifiers = ["bold"] }
"markup.italic" = { fg = "#cccccc", modifiers = ["italic"] }
"markup.heading" = { fg = "#f6f655", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#222222", fg = "#cccccc" }
"markup.heading.hover" = { bg = "#363d59" }
"markup.link" = { fg = "#7575FF" }
"markup.link.label" = { fg = "#55f6f6" }
"markup.link.text" = { fg = "#55f6f6" }
"markup.link.url" = { fg = "#7575FF", underline = { style = "line" } }
"markup.list" = { fg = "#a6f655" }
"markup.normal.completion" = { fg = "#565f89" }
"markup.normal.hover" = { fg = "#a9b1d6" }
"markup.raw" = { fg = "#B26EF7" }
"markup.raw.inline" = { bg = "#303050", fg = "#ccccccff" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

[palette]
background= "{}"
foreground = "#cccccc"
fg = "#cccccc"
fgdim = "#777777"
red = "#f65555"
orange ="#f6a655"
green = "#a6f655"
yellow = "#f6f655"
blue = "#7575FF"
purple = "#B26EF7"
magenta = "#f655f6"
cyan = "#55f6f6"

